"""Generate public/m3/tokens.css from Jetpack Compose Material 3's token sources.

The tokens in androidx (compose/material3/.../tokens/*.kt) are generated by
Google from the Material Design 3 specification. This script reads the
system tokens (colour schemes, type scale, shapes, state layers, motion
springs) at a pinned commit and writes them as CSS custom properties named
like Material Web's (--md-sys-*).

    python tools/m3-tokens.py            # uses the pinned commit below
    python tools/m3-tokens.py <sha>      # or another androidx commit

Component values (button heights, menu shapes, …) are not generated: they are
written by hand in public/m3/m3.css, each with the Compose token it comes from.
"""

import math
import re
import sys
import urllib.request
from pathlib import Path

COMMIT = sys.argv[1] if len(sys.argv) > 1 else "df73c2438e78ba644a436dc402ede6ba2d472812"
BASE = (f"https://raw.githubusercontent.com/androidx/androidx/{COMMIT}/"
        "compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/tokens/")
OUT = Path(__file__).resolve().parent.parent / "public" / "m3" / "tokens.css"

sources = []  # file names read, for the header
copyrights = set()  # "Copyright 2021 The Android Open Source Project", ...


def fetch(name):
    with urllib.request.urlopen(BASE + name + ".kt", timeout=30) as r:
        text = r.read().decode("utf-8")
    sources.append(name + ".kt")
    m = re.search(r"Copyright \d{4} The Android Open Source Project", text)
    if not m:
        sys.exit(f"{name}.kt: no AOSP copyright line")
    copyrights.add(m.group(0))
    return text


def values(source):
    """{Name: "expression"} for every `val Name … = expression` in a token object."""
    source = re.sub(r"//.*", "", source)
    found = {}
    for m in re.finditer(r"val (\w+)\s*(?::[^=\n]*)?(?:\n\s*get\(\))?\s*=\s*([^\n]+)", source):
        found[m.group(1)] = m.group(2).strip()
    return found


def kebab(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "-", name).lower()


# ---------- colour ----------

palette = {}
for name, expr in values(fetch("PaletteTokens")).items():
    m = re.match(r"Color\(red = (\d+), green = (\d+), blue = (\d+)\)", expr)
    if m:
        palette[name] = "#%02x%02x%02x" % tuple(int(v) for v in m.groups())


def scheme(name):
    out = {}
    raw = values(fetch(name))
    for role, expr in raw.items():
        ref = expr.replace("PaletteTokens.", "")
        if ref in palette:
            out[role] = palette[ref]
    for role, expr in raw.items():  # SurfaceTint = Primary
        if role not in out and expr in out:
            out[role] = out[expr]
    return out


light = scheme("ColorLightTokens")
dark = scheme("ColorDarkTokens")
light.setdefault("Shadow", palette["Neutral0"])
dark.setdefault("Shadow", palette["Neutral0"])


def colour_block(colours):
    return "\n".join(f"  --md-sys-color-{kebab(k)}: {v};" for k, v in sorted(colours.items()))


# ---------- type scale ----------

weights = {"WeightRegular": 400, "WeightMedium": 500, "WeightBold": 700}
type_lines = []
for name, expr in values(fetch("TypeScaleTokens")).items():
    m = re.match(r"(\w+?)(LineHeight|Size|Tracking|Weight)$", name)
    if not m:
        continue
    role, prop = kebab(m.group(1)), m.group(2)
    if prop == "Weight":
        value = str(weights[expr.replace("TypefaceTokens.", "")])
    else:
        number = float(re.match(r"(-?\d+(?:\.\d+)?)", expr).group(1))
        # sp maps to CSS px at the default text size; tracking is in sp too.
        value = f"{number:g}px"
    type_lines.append(f"  --md-sys-typescale-{role}-{kebab(prop)}: {value};")
type_lines.sort()

# ---------- shape ----------

shape_lines = []
for name, expr in values(fetch("ShapeTokens")).items():
    m = re.match(r"CornerValue(\w+)", name)
    if m:
        size = re.search(r"([\d.]+)\.dp", expr)
        shape_lines.append(f"  --md-sys-shape-corner-{kebab(m.group(1))}: {float(size.group(1)):g}px;")
shape_lines.append("  --md-sys-shape-corner-full: 9999px;")

# ---------- state layers ----------

state_lines = []
for name, expr in values(fetch("StateTokens")).items():
    m = re.match(r"(\w+)StateLayerOpacity", name)
    if m:
        state_lines.append(f"  --md-sys-state-{kebab(m.group(1))}-state-layer-opacity: {float(expr.rstrip('f')):g};")

# ---------- motion: springs -> CSS linear() ----------
#
# Compose animates with physical springs (stiffness, damping ratio; unit
# mass). CSS cannot, so each spring is sampled into a linear() easing, with
# the duration set to the time the spring takes to settle (within 0.1%).


def spring(stiffness, damping):
    w0 = math.sqrt(stiffness)
    if damping < 1:
        wd = w0 * math.sqrt(1 - damping * damping)
        return lambda t: 1 - math.exp(-damping * w0 * t) * (math.cos(wd * t) + damping * w0 / wd * math.sin(wd * t))
    return lambda t: 1 - math.exp(-w0 * t) * (1 + w0 * t)


def settle_time(x):
    t, step, last_out = 0.0, 0.001, 0.0
    while t < 3:
        if abs(x(t) - 1) > 0.001:
            last_out = t
        t += step
    return last_out


def linear_easing(x, duration, samples=48):
    points = [x(duration * i / samples) for i in range(samples + 1)]
    points[-1] = 1
    return "linear(" + ", ".join(f"{p:.4f}".rstrip("0").rstrip(".") if p else "0" for p in points) + ")"


motion = values(fetch("ExpressiveMotionTokens"))
motion_lines = []
for speed in ("Fast", "Default", "Slow"):
    for kind in ("Spatial", "Effects"):
        k = float(motion[f"Spring{speed}{kind}Stiffness"].rstrip("f"))
        z = float(motion[f"Spring{speed}{kind}Damping"].rstrip("f"))
        x = spring(k, z)
        duration = settle_time(x)
        prefix = f"--md-sys-motion-spring-{speed.lower()}-{kind.lower()}"
        motion_lines.append(f"  /* stiffness {k:g}, damping ratio {z:g} */")
        motion_lines.append(f"  {prefix}: {linear_easing(x, duration)};")
        motion_lines.append(f"  {prefix}-duration: {round(duration * 1000)}ms;")

source_list = "\n".join(f" *   {name}" for name in sources)
copyright_lines = "\n".join(f" * {line}" for line in sorted(copyrights))
css = f"""/* Material Design 3 system tokens.
 *
 * AUTO-GENERATED by tools/m3-tokens.py. Do not edit by hand; re-run the script.
 *
 * Source: Jetpack Compose Material 3 design tokens
 *   https://github.com/androidx/androidx at commit {COMMIT}
 *   compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/tokens/
{source_list}
{copyright_lines}
 * Licensed under the Apache License, Version 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * Changes from the source: values converted to CSS custom properties (dp and sp
 * as px); springs sampled into linear() easings; elevation shadows are not in
 * the source and are written by hand below.
 *
 * Theme: <html class="theme-light | theme-dark | theme-auto">. */

:root {{
{chr(10).join(type_lines)}

{chr(10).join(shape_lines)}

{chr(10).join(state_lines)}

  /* Expressive motion scheme (MotionScheme.expressive()). Spatial springs
   * (position, size, shape) overshoot; effects springs (colour, opacity) do not. */
{chr(10).join(motion_lines)}

  /* Elevation shadows (Compose draws these natively; values from the M3 web spec). */
  --md-sys-elevation-level0: none;
  --md-sys-elevation-level1: 0 1px 2px 0 color-mix(in srgb, var(--md-sys-color-shadow) 30%, transparent), 0 1px 3px 1px color-mix(in srgb, var(--md-sys-color-shadow) 15%, transparent);
  --md-sys-elevation-level2: 0 1px 2px 0 color-mix(in srgb, var(--md-sys-color-shadow) 30%, transparent), 0 2px 6px 2px color-mix(in srgb, var(--md-sys-color-shadow) 15%, transparent);
  --md-sys-elevation-level3: 0 1px 3px 0 color-mix(in srgb, var(--md-sys-color-shadow) 30%, transparent), 0 4px 8px 3px color-mix(in srgb, var(--md-sys-color-shadow) 15%, transparent);
}}

/* Light colour scheme (ColorLightTokens) */
:root,
.theme-light {{
  color-scheme: light;
{colour_block(light)}
}}

/* Dark colour scheme (ColorDarkTokens) */
.theme-dark {{
  color-scheme: dark;
{colour_block(dark)}
}}
@media (prefers-color-scheme: dark) {{
  .theme-auto {{
    color-scheme: dark;
{chr(10).join("  " + line for line in colour_block(dark).splitlines())}
  }}
}}
"""

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(css, encoding="utf-8", newline="\n")
print(f"wrote {OUT} ({len(css)} bytes)")
